spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
#  datasource:
#    url: jdbc:sqlite:memory:isolation_level_demo
#    url: jdbc:h2:mem:isolation_level_demo;DB_CLOSE_DELAY=-1
#    url: jdbc:hsqldb:mem:isolation_level_demo
#    url: jdbc:derby:memory:isolation_level_demo;create=true
